[package]
name = "spotify_sort"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
image-compare = "0.4.1"
lab = "0.11.0"
reqwest = { version = "0.12.10", features = ["json"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
